### ISSUE TITLE
Build in prod impediments after migrate to Angular 7.2.0

### ISSUE THREAD

**Issue by GetTaxSolutions** [MarkPieszak/aspnetcore-angular-universal#716]
I get clean cloning of the repository. Install all packages and start:
`npm run build:prod`
It show follow error:

> ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.3.0 but 3.3.3 was found instead.

If you try to pin typescript to version 3.1.3 removing ^ it's working.

**Comment by GetTaxSolutions** [comment]
Also after that I'm retrieving one other error:

> ERROR in Module build failed (from ./node_modules/css-loader/dist/cjs.js):
    ValidationError: CSS Loader Invalid Options

Maybe because of this: [css-loader issue minimize option](https://github.com/nozzle/react-static/pull/884)

But this is in my separate project and It's not appear in boilerplate. Just checking what is the difference between both projects .

**Comment by alexbenitez** [comment]
@GetTaxSolutions having exactly the same issue... (also separate project based on the starter v6). Getting the "Angular Compiler requires Typescript... " error and after pinning to 3.1.3 then I got the css-loader error....

So far I have only updated the package.json with the new versions... not sure if there is something relevant that I need to modify yet..

Have you found a workaround/fix?

**Comment by GetTaxSolutions** [comment]
For now I just removed 'minimize' parameter from css-loader?minimize and it's working.

**Comment by alexbenitez** [comment]
Thanks @GetTaxSolutions. Now I realized were this parameter was... as a workaround I renamed my “css” file extensions to scss to prevent using the css-loader since I had a mix anyway but your solution I a lot better since it allows css support.

Thx!

**Comment by alexbenitez** [comment]
I started to get back the error and in addition I needed to downgrade typescript as follows:
```
npm install typescript@">=3.1.1 <3.3.0" --save-dev
```

I forgot that I had done this but realized it was also needed when tried from a different machine... typescript update AND the css-loader were my issues in my case.

**Comment by peterblazejewicz** [comment]
@GetTaxSolutions 
Let me know if branch from #718  works for you,
Thanks!

**Comment by GetTaxSolutions** [comment]
It's OK

**Comment by MarkPieszak** [comment]
Sorry for the delay all!! I merged in @peterblazejewicz fix - let me know if everything is ok with that?

**Comment by GetTaxSolutions** [comment]
It's OK for me

**Comment by alexbenitez** [comment]
Thanks @MarkPieszak . It works like a charm!
